- name: CIS Debian Linux 13 (Trixie) Benchmark v1.0 Server L1
  hosts: localhost
  vars_files:
    - "./options/kernel_module_options.yaml"
    - "./options/fs_options.yaml"
    - "./options/bootloader_options.yaml"
    - "./options/coredump_options.yaml"
    - "./options/motd_options.yaml"
    - "./options/service_options.yaml"
    - "./options/client_service_options.yaml"
    - "./options/timesync_options.yaml"
    - "./options/cron_options.yaml"

  tasks:
    - name: "Asserting Options..."
      ansible.builtin.include_tasks:
        file: "./tasks/assert_options.yaml"

    - name: "Section 1.1"
      ansible.builtin.include_tasks:
        file: "./sections/section_1.1.yaml"
      tags:
        - 1.1

    - name: "Section 1.2"    
      ansible.builtin.include_tasks:
        file: "./sections/section_1.2.yaml"
      tags:
        - 1.2

    - name: "Section 1.3"
      ansible.builtin.include_tasks:
        file: "./sections/section_1.3.yaml"
      tags:
        - 1.3

    - name: "Section 1.4"
      ansible.builtin.include_tasks:
        file: "./sections/section_1.4.yaml"
      tags:
        - 1.4
    
    - name: "Section 1.5"
      ansible.builtin.include_tasks:
        file: "./sections/section_1.5.yaml"
      tags:
        - 1.5

    - name: "Section 1.6"
      ansible.builtin.include_tasks:
        file: "./sections/section_1.6.yaml"
      tags:
        - 1.6

    - name: "Section 2.1"
      ansible.builtin.include_tasks:
        file: "./sections/section_2.1.yaml"
      tags:
        - 2.1

    - name: "Section 2.2"
      ansible.builtin.include_tasks:
        file: "./sections/section_2.2.yaml"
      tags:
        - 2.2

    - name: "Section 2.3"
      ansible.builtin.include_tasks:
        file: "./sections/section_2.3.yaml"
      tags: 
        - 2.3
