- name: CIS Debian Linux 13 (Trixie) Benchmark v1.0 Server L1
  hosts: localhost

  handlers:
    - name: "Include handlers..."
      ansible.builtin.import_tasks:
        file: "./handlers/handlers.yaml"

  tasks:
    - name: "Loading options..."
      ansible.builtin.include_vars:
        dir: "./options"
        extensions:
          - "yml"
          - "yaml"
      tags: 
        - always
        - options

    - name: "Asserting options..."
      ansible.builtin.import_tasks:
        file: "./tasks/assert_options.yaml"
      tags: 
        - always
        - assert

    - name: "Section 1.1"
      ansible.builtin.import_tasks:
        file: "./sections/section_1.1.yaml"
      tags:
        - "1.1"

    - name: "Section 1.2"
      ansible.builtin.import_tasks:
        file: "./sections/section_1.2.yaml"
      tags:
        - "1.2"

    - name: "Section 1.3"
      ansible.builtin.import_tasks:
        file: "./sections/section_1.3.yaml"
      tags:
        - "1.3"
        - "1.4" # 1.4 requires 1.3

    - name: "Section 1.4"
      ansible.builtin.import_tasks:
        file: "./sections/section_1.4.yaml"
      tags:
        - "1.4"

    - name: "Section 1.5"
      ansible.builtin.import_tasks:
        file: "./sections/section_1.5.yaml"
      tags:
        - "1.5"

    - name: "Section 1.6"
      ansible.builtin.import_tasks:
        file: "./sections/section_1.6.yaml"
      tags:
        - "1.6"

    - name: "Section 2.1"
      ansible.builtin.import_tasks:
        file: "./sections/section_2.1.yaml"
      tags:
        - "2.1"

    - name: "Section 2.2"
      ansible.builtin.import_tasks:
        file: "./sections/section_2.2.yaml"
      tags:
        - "2.2"

    - name: "Section 2.3"
      ansible.builtin.import_tasks:
        file: "./sections/section_2.3.yaml"
      tags:
        - "2.3"

    - name: "Section 2.4"
      ansible.builtin.import_tasks:
        file: "./sections/section_2.4.yaml"
      tags:
        - "2.4"

    - name: "Section 3.1"
      ansible.builtin.import_tasks:
        file: "./sections/section_3.1.yaml"
      tags:
        - "3.1"

    - name: "Section 3.2"
      ansible.builtin.import_tasks:
        file: "./sections/section_3.2.yaml"
      tags:
        - "3.2"

    - name: "Section 3.3"
      ansible.builtin.import_tasks:
        file: "./sections/section_3.3.yaml"
      tags:
        - "3.3"

    - name: "Section 4.1"
      ansible.builtin.import_tasks:
        file: "./sections/section_4.1.yaml"
      tags:
        - "4.1"

    - name: "Section 5.1"
      ansible.builtin.import_tasks:
        file: "./sections/section_5.1.yaml"
      tags:
        - "5.1"

    - name: "Section 5.2"
      ansible.builtin.import_tasks:
        file: "./sections/section_5.2.yaml"
      tags:
        - "5.2"

    - name: "Section 5.3"
      ansible.builtin.import_tasks:
        file: "./sections/section_5.3.yaml"
      tags:
        - "5.3"

    - name: "Section 5.4"
      ansible.builtin.import_tasks:
        file: "./sections/section_5.4.yaml"
      tags:
        - "5.4"

    - name: "Section 6.1"
      ansible.builtin.import_tasks:
        file: "./sections/section_6.1.yaml"
      tags:
        - "6.1"

    - name: "Section 7.1"
      ansible.builtin.import_tasks:
        file: "./sections/section_7.1.yaml"
      tags:
        - "7.1"
