- name: test
  hosts: localhost
  vars_files:
    - "./options/kernel_module_options.yaml"
    - "./options/fs_options.yaml"
    - "./options/bootloader_options.yaml"
    - "./options/coredump_options.yaml"
    - "./options/motd_options.yaml"
    - "./options/service_options.yaml"
    - "./options/client_service_options.yaml"
    - "./options/timesync_options.yaml"
    - "./options/cron_options.yaml"

  tasks:
    - name: "test one section"
      ansible.builtin.include_tasks:
        file: "./sections/section_2.1.yaml"
