- name: "Asserting options..."
  register: assertions
  ansible.builtin.assert:
    that:
      - require_overlay | bool in [true, false]
      - require_squashfs | bool in [true, false]
      - require_udf | bool in [true, false]
      - require_cramfs | bool in [true, false]
      - require_freevxfs | bool in [true, false]
      - require_hfs | bool in [true, false]
      - require_hfsplus | bool in [true, false]
      - require_jffs2 | bool in [true, false]
      - require_firewire_core | bool in [true, false]
      - require_usb_storage | bool in [true, false]
      - tmp_size | lower is match("^\d{1,}[gmk]$")
      - shm_size | lower is match("^\d{1,}[gmk]$")
      - is_home_partition | bool in [true, false]
      - is_tmp_partition | bool in [true, false]
      - is_var_tmp_partition | bool in [true, false]
      - is_var_log_partition | bool in [true, false]
      - is_var_log_audit_partition | bool in [true, false]
      - is_var_partition | bool in [true, false]
      - bootloader_pbkdf2 is match("^grub.pbkdf2.*")
      - require_coredump | bool in [true, false]
      - require_motd | bool in [true, false]
      - require_autofs | bool in [true, false]
      - run_autofs | bool in [true, false]
      - require_avahi_daemon | bool in [true, false]
      - run_avahi_daemon | bool in [true, false]
      - require_dhcp | bool in [true, false]
      - run_dhcp | bool in [true, false]
      - require_dns | bool in [true, false]
      - run_dns | bool in [true, false]
      - require_dnsmasq | bool in [true, false]
      - run_dnsmasq | bool in [true, false]
      - require_ftp | bool in [true, false]
      - run_ftp | bool in [true, false]
      - require_ldap | bool in [true, false]
      - run_ldap | bool in [true, false]
      - require_pop3 | bool in [true, false]
      - run_pop3 | bool in [true, false]
      - require_imap | bool in [true, false]
      - run_imap | bool in [true, false]
      - require_nfs | bool in [true, false]
      - run_nfs | bool in [true, false]
      - require_nis | bool in [true, false]
      - run_nis | bool in [true, false]
      - require_cups | bool in [true, false]
      - run_cups | bool in [true, false]
      - require_rpcbind | bool in [true, false]
      - run_rpcbind | bool in [true, false]
      - require_rsync | bool in [true, false]
      - run_rsync | bool in [true, false]
      - require_samba | bool in [true, false]
      - run_samba | bool in [true, false]
      - require_snmp | bool in [true, false]
      - run_snmp | bool in [true, false]
      - require_telnet | bool in [true, false]
      - run_telnet | bool in [true, false]
      - require_tftp | bool in [true, false]
      - run_tftp | bool in [true, false]
      - require_proxy | bool in [true, false]
      - run_proxy | bool in [true, false]
      - require_nginx | bool in [true, false]
      - run_nginx | bool in [true, false]
      - require_apache | bool in [true, false]
      - run_apache | bool in [true, false]
      - require_xinetd | bool in [true, false]
      - run_xinetd | bool in [true, false]
      - require_internet_mta | bool in [true, false]
      - require_client_nis | bool in [true, false]
      - require_client_rsh | bool in [true, false]
      - require_client_talk | bool in [true, false]
      - require_client_telnet | bool in [true, false]
      - require_client_ldap | bool in [true, false]
      - require_client_ftp | bool in [true, false]
      - use_systemd_timesyncd | bool in [true, false]
      - use_chrony | bool in [true, false]
      - chrony_pools_max_sources is match("^\d+$")
      - use_systemd_timesyncd != use_chrony
      - require_cron | bool in [true, false]
      - is_cron_deny | bool in [true, false]
      - require_at | bool in [true, false]
      - is_at_deny | bool in [true, false]
      - require_ipv6 | bool in [true, false]
      - require_wlan | bool in [true, false]
      - require_bluetooth | bool in [true, false]
      - run_bluetooth | bool in [true, false]
      - require_atm | bool in [true, false]
      - require_can | bool in [true, false]
      - require_dccp | bool in [true, false]
      - require_rds | bool in [true, false]
      - require_sctp | bool in [true, false]
      - require_tipc | bool in [true, false]
      - require_ipv4_forwarding | bool in [true, false]
      - require_ipv4_asym_routing | bool in [true, false]
      - require_ipv6_forwarding | bool in [true, false]
      - require_ufw | bool in [true, false]
      - require_ufw_ssh | bool in [true, false]
      - ufw_ssh_ip is match("(any|(\d{1,3}\.){3}\d{1,3}(\/\d{1,2})?)")
      - require_ufw_routing | bool in [true, false]
      - ssh_client_alive_interval is match("^\d+$")
      - ssh_client_alive_count_max is match("^\d+$")
      - ssh_log_level | lower in ["info", "verbose"]
      - ssh_max_auth_tries is match("^\d$")
      - ssh_max_sessions is match("^\d+$")
      - require_sudo_ldap | bool in [true, false]
      - sudo_log_file | length > 0
      - su_group_name | length > 0
      - sudo_timestamp_timeout is match("^\d+$")
      - faillock_deny is match ("^\d+$")
      - faillock_unlock_time is match ("\d+$")
      - pwquality_difok is match ("\d+$")
      - pwquality_minlen is match ("\d+$")
      - pwquality_minclass is match ("\d+$")
      - pwquality_dcredit is match ("-?\d+$")
      - pwquality_ucredit is match ("-?\d+$")
      - pwquality_ocredit is match ("-?\d+$")
      - pwquality_lcredit is match ("-?\d+$")
      - pwquality_maxrepeat is match ("\d+$")
      - pwquality_maxsequence is match ("\d+$")
      - pwquality_dictcheck is match ("\d+$")
      - pwquality_enforcing is match ("\d+$")
      - pwquality_enforce_for_root is match ("\d+$")
      - pwhistory_remember is match ("\d+$")
      - pwhistory_enforce_for_root is match ("\d+$")
      - pwhistory_use_authtok is match ("\d+$")
      - shadow_pass_max_days is match ("\d+$")
      - shadow_pass_min_days is match ("\d+$")
      - shadow_pass_warn_age is match ("\d+$")
      - shadow_inactive is match ("\d+$")
      - is_root_breakglass | bool in [true, false]
 
    fail_msg:
      - "Ensure that options are correctly set in each option.yaml. See README.md and each option.yaml file."
