- name: "..."
  ansible.builtin.assert:
    that:
      - require_overlay | lower in ['yes', 'no']
      - require_squashfs | lower in ['yes', 'no']
      - require_udf | lower in ['yes', 'no']
      - tmp_size | lower is match("^\d{1,}[gmk]$")
      - shm_size | lower is match("^\d{1,}[gmk]$")
      - is_home_partition | lower in ['yes', 'no']
      - is_var_tmp_partition | lower in ['yes', 'no']
      - is_var_log_partition | lower in ['yes', 'no']
      - is_var_log_audit_partition | lower in ['yes', 'no']
      - is_var_partition | lower in ['yes', 'no']
      - bootloader_pbkdf2 is match("^grub.pbkdf2.*")
      - require_coredump | lower in ['yes', 'no']
      - require_motd | lower in ['yes', 'no']
      - require_autofs | lower in ['yes', 'no']
      - run_autofs | lower in ['yes', 'no']
      - require_avahi_daemon | lower in ['yes', 'no']
      - run_avahi_daemon | lower in ['yes', 'no']
      - require_dhcp | lower in ['yes', 'no']
      - run_dhcp | lower in ['yes', 'no']
      - require_dns | lower in ['yes', 'no']
      - run_dns | lower in ['yes', 'no']
      - require_dnsmasq | lower in ['yes', 'no']
      - run_dnsmasq | lower in ['yes', 'no']
      - require_ftp | lower in ['yes', 'no']
      - run_ftp | lower in ['yes', 'no']
      - require_ldap | lower in ['yes', 'no']
      - run_ldap | lower in ['yes', 'no']
      - require_pop3 | lower in ['yes', 'no']
      - run_pop3 | lower in ['yes', 'no']
      - require_imap | lower in ['yes', 'no']
      - run_imap | lower in ['yes', 'no']
      - require_nfs | lower in ['yes', 'no']
      - run_nfs | lower in ['yes', 'no']
      - require_nis | lower in ['yes', 'no']
      - run_nis | lower in ['yes', 'no']
      - require_cups | lower in ['yes', 'no']
      - run_cups | lower in ['yes', 'no']
      - require_rpcbind | lower in ['yes', 'no']
      - run_rpcbind | lower in ['yes', 'no']
      - require_rsync | lower in ['yes', 'no']
      - run_rsync | lower in ['yes', 'no']
      - require_samba | lower in ['yes', 'no']
      - run_samba | lower in ['yes', 'no']
      - require_snmp | lower in ['yes', 'no']
      - run_snmp | lower in ['yes', 'no']
      - require_telnet | lower in ['yes', 'no']
      - run_telnet | lower in ['yes', 'no']
      - require_tftp | lower in ['yes', 'no']
      - run_tftp | lower in ['yes', 'no']
      - require_proxy | lower in ['yes', 'no']
      - run_proxy | lower in ['yes', 'no']
      - require_nginx | lower in ['yes', 'no']
      - run_nginx | lower in ['yes', 'no']
      - require_apache | lower in ['yes', 'no']
      - run_apache | lower in ['yes', 'no']
      - require_xinetd | lower in ['yes', 'no']
      - run_xinetd | lower in ['yes', 'no']
      - require_internet_mta | lower in ['yes', 'no']
    fail_msg:
      - "Ensure that options are correctly set in each option.yaml. See README.md and each option.yaml file."
