- name: "..."
  register: assertions
  ansible.builtin.assert:
    that:
      - require_overlay | bool in [true, false]
      - require_squashfs | bool in [true, false]
      - require_udf | bool in [true, false]
      - tmp_size | lower is match("^\d{1,}[gmk]$")
      - shm_size | lower is match("^\d{1,}[gmk]$")
      - is_home_partition | bool in [true, false]
      - is_var_tmp_partition | bool in [true, false]
      - is_var_log_partition | bool in [true, false]
      - is_var_log_audit_partition | bool in [true, false]
      - is_var_partition | bool in [true, false]
      - bootloader_pbkdf2 is match("^grub.pbkdf2.*")
      - require_coredump | bool in [true, false]
      - require_motd | bool in [true, false]
      - require_autofs | bool in [true, false]
      - run_autofs | bool in [true, false]
      - require_avahi_daemon | bool in [true, false]
      - run_avahi_daemon | bool in [true, false]
      - require_dhcp | bool in [true, false]
      - run_dhcp | bool in [true, false]
      - require_dns | bool in [true, false]
      - run_dns | bool in [true, false]
      - require_dnsmasq | bool in [true, false]
      - run_dnsmasq | bool in [true, false]
      - require_ftp | bool in [true, false]
      - run_ftp | bool in [true, false]
      - require_ldap | bool in [true, false]
      - run_ldap | bool in [true, false]
      - require_pop3 | bool in [true, false]
      - run_pop3 | bool in [true, false]
      - require_imap | bool in [true, false]
      - run_imap | bool in [true, false]
      - require_nfs | bool in [true, false]
      - run_nfs | bool in [true, false]
      - require_nis | bool in [true, false]
      - run_nis | bool in [true, false]
      - require_cups | bool in [true, false]
      - run_cups | bool in [true, false]
      - require_rpcbind | bool in [true, false]
      - run_rpcbind | bool in [true, false]
      - require_rsync | bool in [true, false]
      - run_rsync | bool in [true, false]
      - require_samba | bool in [true, false]
      - run_samba | bool in [true, false]
      - require_snmp | bool in [true, false]
      - run_snmp | bool in [true, false]
      - require_telnet | bool in [true, false]
      - run_telnet | bool in [true, false]
      - require_tftp | bool in [true, false]
      - run_tftp | bool in [true, false]
      - require_proxy | bool in [true, false]
      - run_proxy | bool in [true, false]
      - require_nginx | bool in [true, false]
      - run_nginx | bool in [true, false]
      - require_apache | bool in [true, false]
      - run_apache | bool in [true, false]
      - require_xinetd | bool in [true, false]
      - run_xinetd | bool in [true, false]
      - require_internet_mta | bool in [true, false]
      - require_client_nis | bool in [true, false]
      - require_client_rsh | bool in [true, false]
      - require_client_talk | bool in [true, false]
      - require_client_telnet | bool in [true, false]
      - require_client_ldap | bool in [true, false]
      - require_client_ftp | bool in [true, false]
      - use_systemd_timesyncd | bool in [true, false]
      - use_chrony | bool in [true, false]
      - chrony_pools_max_sources is match("^\d+$")
      - use_systemd_timesyncd != use_chrony 
      - require_cron | bool in [true, false]
      - is_cron_deny | bool in [true, false]
      - require_at | bool in [true, false]
      - is_at_deny | bool in [true, false]
    fail_msg:
      - "Ensure that options are correctly set in each option.yaml. See README.md and each option.yaml file."
