- name: "Updating {{ fs }} in /etc/fstab..."
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^{{ fs | regex_escape }}\s+{{ mountpoint | regex_escape }}\s+{{ type | regex_escape }}.*\s+\d\s+\d$'
    state: present
    line: "{{ fs }} {{ mountpoint }} {{ type }} errors=remount-ro,nosuid,nodev,noexec 0 1"
