- name: "Ensuring systemd-timesyncd exists..."
  ansible.builtin.apt:
    name: "systemd-timesyncd"
    state: present

- name: "Ensuring chrony is masked..."
  ignore_errors: true
  ansible.builtin.systemd_service:
    name: "chronyd.service"
    state: stopped
    enabled: false
    masked: true

- name: "Ensuring systemd-timesyncd is active..."
  ansible.builtin.systemd_service:
    name: "systemd-timesyncd.service"
    state: started
    enabled: true
    masked: false

- name: "Configuring systemd-timesyncd primary NTP..."
  register: timesyncd_primary
  community.general.ini_file:
    path: "/etc/systemd/timesyncd.conf.d/99-timesyncd.conf"
    section: Time
    option: NTP
    value: "{{ timesyncd_primary }}"
    state: present

- name: "Configuring systemd-timesyncd fallback NTP..."
  register: timesyncd_fallback
  community.general.ini_file:
    path: "/usr/lib/systemd/timesyncd.conf.d/99-timesyncd.conf"
    section: Time
    option: FallbackNTP
    value: "{{ timesyncd_fallback }}"
    state: present

- name: "Restarting systemd-timesyncd..."
  ansible.builtin.systemd_service:
    name: "systemd-timesyncd.service"
    state: restarted
    enabled: true
    daemon-reload: true
    masked: false
  when: timesyncd_primary.changed or timesyncd_fallback.changed

