- name: "Ensuring systemd-timesyncd exists..."
  ansible.builtin.apt:
    name: "systemd-timesyncd"
    state: present

- name: "Ensuring systemd-timesyncd is active..."
  ansible.builtin.systemd_service:
    name: "systemd-timesyncd.service"
    state: started
    enabled: true
    masked: false

- block:
  - name: "Configuring systemd-timesyncd primary NTP..."
    community.general.ini_file:
      path: "/etc/systemd/timesyncd.conf.d/99-timesyncd.conf"
      owner: root
      group: root
      mode: '0644'
      section: Time
      option: NTP
      value: "{{ timesyncd_primary }}"
      state: present

  - name: "Configuring systemd-timesyncd fallback NTP..."
    community.general.ini_file:
      path: "/etc/systemd/timesyncd.conf.d/99-timesyncd.conf"
      owner: root
      group: root
      mode: '0644'
      section: Time
      option: FallbackNTP
      value: "{{ timesyncd_fallback }}"
      state: present

  notify: Restart systemd-timesyncd.service
