- name: "1.5.12 Ensure systemd-coredump ProcessSizeMax is configured"
  community.general.ini_file:
    path: "/etc/systemd/coredump.conf.d/99-cis-coredump.conf"
    section: Coredump
    option: ProcessSizeMax
    value: 0
    state: present

- name: "1.5.13 Ensure systemd-coredump Storage is configured"
  community.general.ini_file:
    path: "/etc/systemd/coredump.conf.d/99-cis-coredump.conf"
    section: Coredump
    option: Storage
    value: none
    state: present
