- name: "Updating {{ fs }} in /etc/fstab..."
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^tmpfs\s+{{ fs | regex_escape }}\s+tmpfs\s+.*\s+\d\s+\d$'
    state: present
    line: "tmpfs {{ fs }} tmpfs defaults,rw,nosuid,nodev,noexec,relatime,size={{ size }}  0 0"
