- name: "Ensuring chrony exists..."
  ansible.builtin.apt:
    name: "chrony"
    state: present

- name: "Ensuring systemd-timesyncd is masked..."
  ansible.builtin.include_tasks:
    file: "../templates/mask_stop_service.yaml"
  vars:
    service: "systemd-timesyncd"

- name: "Ensuring chrony is active..."
  ansible.builtin.systemd_service:
    name: "chrony.service"
    state: started
    enabled: true
    masked: false

- name: "Removing default chrony pools and servers..."
  ansible.builtin.replace:
    path: "/etc/chrony/chrony.conf"
    regexp: '^(pool|server)(.*)$'
    replace: '# \1\2'

- block:
  - name: "Configuring chrony pools..."
    register: chrony_pools_changed
    ansible.builtin.copy:
      dest: "/etc/chrony/sources.d/99-pools.conf"
      owner: root
      group: root
      mode: '0644'
      content: |
        {% for pool in chrony_pools | split(' ') %}
        pool {{ pool }} iburst maxsources {{ chrony_pools_max_sources }}
        {% endfor %}

  - name: "Configuring chrony servers..."
    register: chrony_servers_changed
    ansible.builtin.copy:
      dest: "/etc/chrony/sources.d/99-servers.conf"
      owner: root
      group: root
      mode: '0644'
      content: |
        {% for server in chrony_servers | split(' ') %}
        server {{ server }} iburst
        {% endfor %}

    notify: Restart chrony.service
