- name: "Reading /etc/passwd..."
  ansible.builtin.slurp:
    src: "/etc/passwd"
  register: file

- name: "Decoding content..."
  ansible.builtin.set_fact:
    list: "{{ (file.content | b64decode) | regex_findall('^([^:]+):([^:]+):\\d+:.*$', multiline=True) }}"

- name: "Editing /etc/passwd..."
  ansible.builtin.replace:
    path: "/etc/passwd"
    regexp: '^{{ item[0] | regex_escape }}:[^:]+:(.*$)'
    replace: '{{ item[0] }}:x:\g<1>'
  when: item[1] != "x"
  loop: "{{ list }}"

- name: "Editing /etc/shadow..."
  ansible.builtin.replace:
    path: "/etc/shadow"
    regexp: '^{{ item[0] | regex_escape }}:[^:]+:(.*$)'
    replace: '{{ item[0] }}:{{ item[1] }}:\g<1>'
  when: item[1] != "x"
  loop: "{{ list }}"

