- name: "Restart sshd.service"
  ansible.builtin.systemd_service:
    name: "sshd.service"
    state: restarted

- name: "Restart chrony.service"
  ansible.builtin.systemd_service:
    name: "chrony.service"
    state: restarted

- name: "Restart systemd-timesyncd.service"
  ansible.builtin.systemd_service:
    name: "systemd-timesyncd.service"
    state: restarted

- name: "Restart postfix.service"
  ansible.builtin.systemd_service:
    name: "postfix.service"
    state: restarted

- name: "Restart systemd-coredump.socket"
  ansible.builtin.systemd_service:
    name: "systemd-coredump.socket"
    state: restarted

- name: "Reload systemd daemon"
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "Apply fstab"
  ansible.posix.mount:
    name: "{{ item.mountpoint }}"
    state: remounted
  loop:
    - { mountpoint: "{{ tmp_mount }}", required: "{{ is_tmp_partition }}" }
    - { mountpoint: "{{ home_mount }}", required: "{{ is_home_partition }}" }
    - { mountpoint: "{{ var_mount }}", required: "{{ is_var_partition }}"}
    - { mountpoint: "{{ var_tmp_mount }}", required: "{{ is_var_tmp_partition }}"}
    - { mountpoint: "{{ var_log_mount }}", required: "{{ is_var_log_partition }}" }
    - { mountpoint: "{{ var_log_audit_mount }}", required: "{{ is_var_log_audit_partition }}" }
  when: item.required | bool
