- name: "2.2.1 Ensure nis client is not installed"
  ansible.builtin.apt:
    name: "nis"
    state: absent
    purge: true
  when: not (require_client_nis | bool)

- name: "2.2.2 Ensure rsh client is not installed"
  ansible.builtin.apt:
    name: "rsh"
    state: absent
    purge: true
  when: not (require_client_rsh | bool)

- name: "2.2.3 Ensure talk client is not installed"
  ansible.builtin.apt:
    name: "talk"
    state: absent
    purge: true
  when: not (require_client_talk | bool)

- name: "2.2.4 Ensure telnet client is not installed"
  ansible.builtin.apt:
    name: "{{ client_service }}"
    state: absent
    purge: true
  when: not (require_client_telnet | bool)
  vars:
    client_service:
      - "telnet"
      - "inetutils-telnet"

- name: "2.2.5 Ensure ldap client is not installed"
  ansible.builtin.apt:
    name: "ldap-util"
    state: absent
    purge: true
  when: not (require_client_ldap | bool)

- name: "2.2.6 Ensure ftp client is not installed"
  ansible.builtin.apt:
    name: "{{ client_service }}"
    state: absent
    purge: true
  when: not (require_client_ftp | bool)
  vars:
    client_service:
      - "tnftp"
      - "ftp"
