- name: "1.3.1.1 Ensure apparmor packages are installed"
  ansible.builtin.apt:
    name: "apparmor"
    state: present

- name: "1.3.1.2 Ensure apparmor is enabled"
  register: aa_enabled
  ansible.builtin.lineinfile:
    path: "/etc/default/grub"
    regexp: ^(GRUB_CMDLINE_LINUX=.*)apparmor=0(.*$)
    line: \1apparmor=1 security=apparmor\2
    backrefs: true

- name: "1.3.1.4 Ensure apparmor_restrict_unprivileged_unconfined is enabled"
  ansible.builtin.include_tasks:
    file: "../templates/configure_sysctl_settings.yaml"
  vars:
    setting: "kernel.apparmor_restrict_unprivileged_unconfined"
    value: "1"
