- name: "7.2.1 Ensure accounts in /etc/passwd use shadowed passwords"
  ansible.builtin.include_tasks:
    file: "../tasks/convert_to_shadow.yaml"

- name: "7.2.2 Ensure /etc/shadow password fields are not empty"
  ansible.builtin.replace:
    path: "/etc/shadow"
    regexp: '^([^:]+)::(.*$)'
    replace: '\1:*:\2'

- name: "7.2.4 Ensure shadow group is empty"
  ansible.builtin.replace:
    path: "/etc/shadow"
    regexp: '^(shadow:x:\d+:).*$'
    replace: '\1'

- name: "7.2.9 Ensure local interactive user home directories are configured"
  ansible.builtin.include_tasks:
    file: "../tasks/configure_home_directories.yaml"
