- name: "Installing cron..."
  ansible.builtin.apt:
    name: "cron"
    state: present
  when: require_cron | bool

- name: "Installing at..."
  ansible.builtin.apt:
    name: "at"
    state: present
  when: require_at | bool

- name: "Uninstalling cron..."
  ansible.builtin.apt:
    name: "cron"
    state: absent
    purge: true
  when: not (require_cron | bool)

- name: "Uninstalling at..."
  ansible.builtin.apt:
    name: "at"
    state: absent
    purge: true
  when: not (require_at | bool)

- block: 
  - name: "2.4.1.1 Ensure cron daemon is enabled and active"
    ansible.builtin.systemd_service:
      name: "cron"
      state: "started"
      masked: false
      enabled: true

  - name: "2.4.1.2 Ensure access to /etc/crontab is configured"
    ansible.builtin.file:
      path: "/etc/crontab"
      mode: '0600'
      owner: root
      group: root

  - name: "2.4.1.3 Ensure access to /etc/cron.hourly is configured"
    ansible.builtin.file:
      path: "/etc/cron.hourly"
      state: directory
      recurse: true
      owner: root
      group: root
      mode: u=rwX,o=,g=

  - name: "2.4.1.4 Ensure access to /etc/cron.daily is configured"
    ansible.builtin.file:
      path: "/etc/cron.daily"
      state: directory
      recurse: true
      owner: root
      group: root
      mode: u=rwX,o=,g=

  - name: "2.4.1.5 Ensure access to /etc/cron.weekly is configured"
    ansible.builtin.file:
      path: "/etc/cron.weekly"
      state: directory
      recurse: true
      owner: root
      group: root
      mode: u=rwX,o=,g=
 
  - name: "2.4.1.6 Ensure access to /etc/cron.monthly is configured"
    ansible.builtin.file:
      path: "/etc/cron.monthly"
      state: directory
      recurse: true
      owner: root
      group: root
      mode: u=rwX,o=,g=
 
  - name: "2.4.1.7 Ensure access to /etc/cron.yearly is configured"
    ansible.builtin.file:
      path: "/etc/cron.yearly"
      state: directory
      recurse: true
      owner: root
      group: root
      mode: u=rwX,o=,g=
 
  - name: "2.4.1.8 Ensure access to /etc/cron.d is configured"
    ansible.builtin.file:
      path: "/etc/cron.d"
      state: directory
      recurse: true
      owner: root
      group: root
      mode: u=rwX,o=,g=

  - name: "2.4.1.9 Ensure access to crontab is configured (cron.allow)"
    ansible.builtin.copy:
      dest: "/etc/cron.allow"
      owner: root
      group: crontab
      mode: '0640'
      content: |
        {% for user in cron_allow | split(' ') %}
        {{ user }}
        {% endfor %}
    when: not (is_cron_deny | bool)

  - name: "Deleting /etc/cron.deny..."
    ansible.builtin.file:
      path: "/etc/cron.deny"
      state: absent
    when: not (is_cron_deny | bool)

  - name: "2.4.1.9 Ensure access to crontab is configured (cron.deny)"
    ansible.builtin.copy:
      dest: "/etc/cron.deny"
      owner: root
      group: crontab
      mode: '0640'
      content: |
        {% for user in cron_deny | split(' ') %}
        {{ user }}
        {% endfor %}
    when: is_cron_deny | bool

  - name: "Deleting /etc/cron.allow..."
    ansible.builtin.file:
      path: "/etc/cron.allow"
      state: absent
    when: is_cron_deny | bool

  when: require_cron | bool

- block: 
  - name: "2.4.2.1 Ensure access to at is configured (at.allow)"
    ansible.builtin.copy:
      dest: "/etc/at.allow"
      owner: root
      group: daemon
      mode: '0640'
      content: |
        {% for user in at_allow | split(' ') %}
        {{ user }}
        {% endfor %}
    when: not (is_at_deny | bool)

  - name: "Deleting /etc/at.deny..."
    ansible.builtin.file:
      path: "/etc/at.deny"
      state: absent
    when: not (is_at_deny | bool)

  - name: "2.4.2.1 Ensure access to at is configured (at.deny)"
    ansible.builtin.copy:
      dest: "/etc/at.deny"
      owner: root
      group: daemon
      mode: '0640'
      content: |
        {% for user in at_deny | split(' ') %}
        {{ user }}
        {% endfor %}
    when: is_at_deny | bool

  - name: "Deleting /etc/at.allow..."
    ansible.builtin.file:
      path: "/etc/at.allow"
      state: absent
    when: is_at_deny | bool
  
  when: require_at | bool
