- name: "Configuring {{ fs }}..."
  ansible.posix.mount:
    path: "{{ mountpoint }}"
    src: "{{ fs }}"
    fstype: "{{ fs_type }}"
    opts: errors=remount-ro,nosuid,nodev,noexec
    state: mounted
