- name: "Getting logs under {{ path }}..."
  register: file_list
  ansible.builtin.find:
    recurse: true
    paths: "{{ path }}"
    patterns: "{{ regex }}"
    use_regex: true

- block:
  - name: "Correcting log ownership..."
    ansible.builtin.file:
      path: "{{ item.path }}"
      owner: "root"
    loop: "{{ file_list.files }}"
    loop_control: 
      label: "{{ item.path }}: {{ item.pw_name }}"
    when: 
      - item.pw_name is not match(owner)
      - owner | length > 0

  - name: "Correcting log group ownership..."
    ansible.builtin.file:
      path: "{{ item.path }}"
      group: "root"
    loop: "{{ file_list.files }}"
    loop_control:
      label: "{{ item.path }}: {{ item.gr_name }}"
    when: 
      - item.gr_name is not match(group) 
      - group | length > 0

  - name: "Correcting log permissions..."
    ansible.builtin.file:
      path: "{{ item.path }}"
      mode: "{{ mode }}"
    loop: "{{ file_list.files }}"
    loop_control:
        label: "{{ item.path }}: {{ item.mode }}"
    when: (item.mode | int(base=8)) > (mode | int(base=8))

  when: 
    - file_list.matched > 0
