- name: "Configuring {{ fs }}..."
  ansible.posix.mount:
    src: "tmpfs"
    path: "{{ fs }}"
    fstype: "tmpfs"
    opts: "defaults,rw,nosuid,nodev,noexec,relatime,size={{ size }}"
    state: mounted
